### PR TITLE
Correct path in README

### PR DESCRIPTION
**Pull request by kasbah**
I think you meant this?

### CODE REVIEW

**Comment by andrewgaul** [comment]
This original path is intended; users can have a passwd file in /etc or anywhere on their file system.

**Comment by kasbah** [comment]
But it should match the path of the command just before, no?

**Comment by kasbah** [comment]
Also, wouldn't `chmod 640` be better? That would match what it says in the man page as well.

**Comment by ggtakec** [comment]
@kasbah Thanks

**Pull request merged**
