### PR TITLE
Add error checking to test_concurrent_writes

### PR DESCRIPTION
**Pull request by gaul**
This reveals a situation where s3fs triggers an unexpected `EntityTooSmall` error.

### CODE REVIEW

**Comment by gaul** [comment]
@ggtakec Could you look into this:

```
[s3proxy] D 08-28 17:00:25.152 S3Proxy-Jetty-27 o.gaul.s3proxy.S3ProxyHandler:2949 |::] sendSimpleErrorResponse: 400 EntityTooSmall Your proposed upload is smaller than the minimum allowed object size. Each part must be at least 5 MB in size, except the last part. {}
dd: closing output file 'test-s3fs-11795.txt': Input/output error
s3fs: [ERR] curl.cpp:RequestPerform(2529): HTTP response code 400, returning EIO. Body Text: <?xml version='1.0' encoding='UTF-8'?><Error><Code>EntityTooSmall</Code><Message>Your proposed upload is smaller than the minimum allowed object size. Each part must be at least 5 MB in size, except the last part.</Message><RequestId>4442587FB7D0A2F9</RequestId></Error>
s3fs: [ERR] fdcache_entity.cpp:RowFlushStreamMultipart(1917): failed to complete multipart upload by errno(-5)
```

**Comment by ggtakec** [comment]
@gaul This is an error that occurred in StreamUpload. I will investigate.

**Comment by ggtakec** [comment]
@gaul Sorry for the late reply.
I have caught the phenomenon that causes the problem. I will investigate the cause and try to fix it.

**Comment by ggtakec** [comment]
I'm late, but I've posted PR for this problem in #2325.

**Comment by ggtakec** [comment]
@gaul The following error seems to occur on CentOS7.
```
./integration-test-main.sh: line 1885: wait: -n: invalid option
```

**Comment by gaul** [comment]
> `./integration-test-main.sh: line 1885: wait: -n: invalid option`

fixed

**Pull request merged**
