### PR TITLE
Add support for ECS metadata endpoint

### PR DESCRIPTION
**Pull request by psyvision**
This pull request resolves the issue of not using the ECS metadata endpoint when running under an ECS task role -> https://github.com/s3fs-fuse/s3fs-fuse/issues/507.

I haven't added any tests, I didn't see any that I thought were similar.

I haven't actually tested this on an ECS task yet - I will do this tomorrow!

### CODE REVIEW

**Comment by psyvision** [comment]
I've just given this a test on our ECS setup and it failed because https://github.com/psyvision/s3fs-fuse/blob/master/src/s3fs.cpp#L4077 in `get_access_keys` is not taking the ecs flag into consideration.

**Comment by psyvision** [comment]
I've almost got this working on ECS.  The current issue is that the ECS metadata endpoint returns JSON formatted onto one line rather than the EC2 endpoint that is returning data on one line per JSON key.  Therefore the function `S3fsCurl::ParseIAMCredentialResponse` is failing.  I will have to write a new version for the ECS.

**Comment by psyvision** [comment]
@ggtakec this is now ready for review I think / hope :)

**Comment by ggtakec** [comment]
@psyvision Thanks for your kindness.
But I'm sorry to keep you waiting, I will review by the end of the week.

**Comment by ggtakec** [comment]
@psyvision I will merge this PR.
I decided that it would not be a problem for jsoncpp to add new additional library.
About MACROs in your codes, I will fix those after merging @gaul PR #675.(I will change those like #675)
Thanks for your kindness.

**Comment by gaul** [comment]
@psyvision Can you add the jsoncpp requirement to the README instructions for Ubuntu and CentOS?

**Comment by psyvision** [comment]
Many thanks for merging!

**Pull request merged**
