### PR TITLE
Upgrade CI to Alpine 3.20

### PR DESCRIPTION
**Pull request by gaul**

### CODE REVIEW

**Comment by gaul** [comment]
Oddly alpine 3.19 has an aws-cli package but 3.20 does not:

https://pkgs.alpinelinux.org/packages?name=aws-cli&branch=v3.19&repo=&arch=&maintainer=

**Comment by ggtakec** [comment]
It seems like it can't be helped. Let's wait a little longer.

**Comment by gaul** [comment]
References aws/aws-cli#8689.

**Comment by gaul** [comment]
Alpine now has packages: https://pkgs.alpinelinux.org/packages?name=aws-cli&branch=v3.20&repo=&arch=&maintainer=

**Pull request merged**
