### PR TITLE
Adds requester_pays option to enable requests involving Requester Pays buckets

### PR DESCRIPTION
**Pull request by ahuarte47**
This PR adds `requester_pays` option, false by default, to enable requests involving Requester Pays buckets.

Related issue:
https://github.com/s3fs-fuse/s3fs-fuse/issues/635

### CODE REVIEW

**Comment by ggtakec** [comment]
@ahuarte47 @3DTOPO I'm sorry for late reply.
I'll merge this PR soon.

**Comment by ahuarte47** [comment]
Thank you very much @ggtakec !

**Comment by cprieger** [comment]
What version will this be available in? 

Sorry this may be a beginner question. But I am also processing some imagery and have come across the same use case.

**Comment by gaul** [comment]
1.86 should include this feature.

**Pull request merged**
