### PR TITLE
Test updating the metadata of an external object

### PR DESCRIPTION
**Pull request by gaul**
References #1453.

### CODE REVIEW

**Comment by gaul** [comment]
Cannot merge until we create a fix.

**Comment by ggtakec** [comment]
@gaul When I synchronize to the master branch, it seems that the build is failing.

**Comment by gaul** [comment]
This is expected to fail until we create a fix.

**Comment by ggtakec** [comment]
@gaul In #1579, a test case including this test item is required, and an extended test code based on this test code has been added to that PR.
Please review test code in that PR.

**Comment by gaul** [comment]
Superseded by #1579.

**Pull request closed without merging**
