### PR TITLE
Address cppcheck 2.10 warnings

### PR DESCRIPTION
**Pull request by gaul**
References #2162.

### CODE REVIEW

**Comment by gaul** [comment]
This is a bit tricky -- old versions of cppcheck don't accept some kinds of suppressions but newer versions require them.  Maybe we could use a per-version suppression file?

**Comment by ggtakec** [comment]
@gaul
It seems that cppcheck's false positives and cppcheck's `--suppress` syntax are not set well, so how about fixing it as follows?
(When I checked, it was able to build without problems.)

- The `Makefile.am` only adds `useStlAlgorithm` and does not change the `unmatchedSuppression` syntax:  
```
--suppress=unmatchedSuppression \
--suppress=useStlAlgorithm \
```

- In `src/fdcache_page.cpp`, cppcheck seems to be confused about the one-liner, so write it with an if statement as follows:  
```
PageList::page_status pstatus = PAGE_NOT_LOAD_MODIFIED;
if(is_loaded && is_modified){
    pstatus = PageList::PAGE_LOAD_MODIFIED;
}else if(!is_loaded && is_modified){
    pstatus = PageList::PAGE_MODIFIED;
}else if(is_loaded && !is_modified){
    pstatus = PageList::PAGE_LOADED;
}
```  
It looks different because it removes the one-liner, but the content is the same, so it shouldn't be a problem.

**Comment by gaul** [comment]
Let's disable newer cppcheck to unbreak CI then we can revisit proper fixes.

**Comment by ggtakec** [comment]
Acknowledged to postpone cppcheck's useStlAlgorithm error handling.
We will discuss this matter later.

**Pull request merged**
