### PR TITLE
Upgrade CI to Alpine 3.18

### PR DESCRIPTION
**Pull request by gaul**
References #2328.

### CODE REVIEW

**Comment by gaul** [comment]
This has an interesting failure in bullseye:

```
stat: cannot statx 'test-s3fs-24610.txt': No such file or directory
```

Maybe similar to the caching issues we have observed earlier?

**Review by Jessb6996 — APPROVED** [review]

**Comment by ggtakec** [comment]
This seems similar to the issue being detected with alpine.
I think that s3fs could not detect the file uploaded from outside(by aws command).
(But I would know if I had the curldbg logs, but the info level logs don't allow me to be sure of this.)

**Comment by ggtakec** [comment]
@gaul Just for quick reference.
I don't know if this will help you, but I cut out the `alpine 3.18` test (`test_mtime_file` and `test_update_time_cp_p` only) on Github Actions and tried that.
(The log setting is `curldbg` and `dbglevel=dbg`.)
https://github.com/ggtakec/s3fs-fuse/actions/runs/6604273488

This result is very strange.
These tests (`test_mtime_file` and `test_update_time_cp_p`) compare the stats of the underlying file object and its copied file object.
The (`PUT` and) `HEAD` requests to the underlying file are being called successfully.
However, the copy file operation is only being called with a `PUT` request.
(Originally, there would be a `HEAD` request after the `PUT`, which would retake the stat information.)

It may be a good idea to check whether there have been any changes to the cache related to the stat command since `alpine 3.18`.

**Comment by ggtakec** [comment]
@gaul 
I have identified the cause of this issue, it has been fixed and posted PR #2361.
Once #2361 is merged, please make this Alpine PR from Draft to official PR.
Thanks in advance for your assistance.

**Comment by gaul** [comment]
Alpine still fails after rebasing:

```
s3fs: [INF] s3fs.cpp:s3fs_getattr(1041): [path=/testrun-7150][pid=2653,uid=0,gid=0]
cp with -p option expected updated ctime: 1000000000.000000000 != 1000000000.000000000 and same mtime: 1000000000.000000000 == 1000000000.000000000, atime: 1000000000.000000000 == 1000000000.000000000

test_update_time_cp_p failed
```

**Comment by ggtakec** [comment]
I think this remaining bug was fixed in #2364.

**Pull request merged**
