### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
### Details

Fix misspellings in code and comments.

### CODE REVIEW

**Comment by ggtakec** [comment]
@szepeviktor Thanks for this PR.
I would like to merge this, but there is a conflict with another PR that was merged just before merging this PR.
Sorry for the inconvenience, but could you rebase(+squash) this PR code?

**Comment by szepeviktor** [comment]
> could you rebase(+squash) this PR code?

Tough! I have to use a computer.

**Comment by szepeviktor** [comment]
... meanwhile somebody contributed another typo!

**Comment by ggtakec** [comment]
@szepeviktor Thanks for the fast response.
I'll merge this.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
