### PR TITLE
Added the function to update mtime/ctime of the parent directory

### PR DESCRIPTION
**Pull request by ggtakec**
### Relevant Issue (if applicable)
#1961 #1962 #1964 #2024

### Details
This fix, the `mtime`/`ctime` of the parent directory is updated when the `i-node` of the parent directory is updated(create/delete files and directories, etc.).

The operation to update `mtime`/`ctime` in the parent directory is shown below:
| Operation                                                                  | ctime/mtime  |
| -------------------------------------------------------------------------- | ------------ |
| Create file/symbolic file/directory(`touch`, `cp`, `ln -s`, `mkdir`, etc)  | update       |
| Rename file/symbolic file/directory(`mv`, etc)                             | update       |
| Update file/symbolic file/directory(`touch`, `chmod`, `chown`, chgrp`, etc)| not update   |

I am adding a test(`test_update_parent_directory_time`) for the above pattern.

This fix will perform updating stats of the parent directory for each operation.
And this updating stats is enabled by default.
However, some users may not need this update stats process, and I have added the option `disable_update_parent_dir_stat` to suppress it.

This PR will resolve the issues in #1961 and #1962.
After #1964 will be merged, this branch will be rebased and release Draft.

This PR contains the same code as #1964.
(This is necessary and dependent it for conducting the test.)

### CODE REVIEW

**Comment by ggtakec** [comment]
@gaul 
I have reviewed the option defaults to reflect the impact of this fix.
As you pointed out, I think the performance impact of this fix is not negligible when moving a directory with a large number of files.
So I disabled this fix(stat update for parent directory) by default.
This is as same as the current behavior of s3fs.

This feature is enabled by adding the option `update_parent_dir_stat`.
To work around update issues with NFS that have been challenged, this option can be granted to resolve.

I'm updating the options when testing to give `update_parent_dir_stat` to run the tests.

Please re-review this PR.

**Review by huntersman — CHANGES_REQUESTED** [review]
I think there is a bug, when I rename the file under mount point, it noticed me that `path(/) is not parent directory.`. Apparently, it returns `-EIO` and S3FS corrupts.
```c++
if(!S_ISDIR(stbuf.st_mode)){
  S3FS_PRN_ERR("path(%s) is not parent directory.", parentpath.c_str());
  return -EIO;
}
```
Maybe we could not change "/" `mtime/ctime`
```c++
std::string root ("/");
if (root.compare(parentpath)==0){
  return 0;
}
if(!S_ISDIR(stbuf.st_mode)){
  S3FS_PRN_ERR("path(%s) is not parent directory.", parentpath.c_str());
  return -EIO;
}
```

**Comment by ggtakec** [comment]
@huntersman Thanks for your kindness.

I tried renaming the file under the mount point, but it seems to work without problems(EIO).
_even if there is no "/" object for the mountpoint._

If you don't mind, could you tell me how to reproduce the EIO you found?
Any hints about s3fs boot options and file operations would be greatly appreciated.

**Comment by huntersman** [comment]
@ggtakec I think it's because #2048, I tried to modify the mount point modified date. For example,
`touch -t 2211110900.00 /mount/bucket` and get `touch: setting times of ‘/mount/bucket’: Input/output error`.

**Comment by ggtakec** [comment]
@huntersman 
Could you restart s3fs with `dbglevel=dbg` and `curldbg` options and show us the log of doing this operation?

I may be overlooking something, but manipulating the mount points works fine for me.
Note that updating mount point stats is a feature that was supported in #1964 PR and has been merged into the current master.
If the code you're trying doesn't have this fix, you'll need to merge this PR code.
Thanks in advance for your assistance.

**Comment by huntersman** [comment]
@ggtakec 
Thank you for your answer, the PR code is merged, but it seems the object storage that I use does not support the request.
```
2022-11-15T01:37:56.332Z [CURL DBG] * Found bundle for host xxxx: 0x7f063c018850
2022-11-15T01:37:56.332Z [CURL DBG] * Re-using existing connection! (#0) with host xxxx
2022-11-15T01:37:56.333Z [CURL DBG] * Connected to xxxx (xxxx) port 80 (#0)
2022-11-15T01:37:56.333Z [CURL DBG] > PUT /demo// HTTP/1.1
2022-11-15T01:37:56.333Z [CURL DBG] > User-Agent: s3fs/1.91 (commit hash 962856b; OpenSSL)
2022-11-15T01:37:56.334Z [CURL DBG] > Accept: */*
2022-11-15T01:37:56.334Z [CURL DBG] > Authorization: AWS4-HMAC-SHA256 Credential=xxxx/20221115/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-atime;x-amz-meta-ctime;x-amz-meta-gid;x-amz-meta-mode;x-amz-meta-mtime;x-amz-meta-uid, Signature=xxxx
2022-11-15T01:37:56.334Z [CURL DBG] > Content-Type: application/x-directory
2022-11-15T01:37:56.334Z [CURL DBG] > host: xxxx
2022-11-15T01:37:56.334Z [CURL DBG] > x-amz-acl: public-read
2022-11-15T01:37:56.334Z [CURL DBG] > x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2022-11-15T01:37:56.335Z [CURL DBG] > x-amz-date: 20221115T013756Z
2022-11-15T01:37:56.335Z [CURL DBG] > x-amz-meta-atime: 1668128400
2022-11-15T01:37:56.335Z [CURL DBG] > x-amz-meta-ctime: 1668128400
2022-11-15T01:37:56.335Z [CURL DBG] > x-amz-meta-gid: 0
2022-11-15T01:37:56.335Z [CURL DBG] > x-amz-meta-mode: 16895
2022-11-15T01:37:56.336Z [CURL DBG] > x-amz-meta-mtime: 1668128400
2022-11-15T01:37:56.336Z [CURL DBG] > x-amz-meta-uid: 0
2022-11-15T01:37:56.336Z [CURL DBG] > Content-Length: 0
2022-11-15T01:37:56.336Z [CURL DBG] > Expect: 100-continue
2022-11-15T01:37:56.336Z [CURL DBG] >
2022-11-15T01:37:56.340Z [CURL DBG] < HTTP/1.1 400 Bad Request
2022-11-15T01:37:56.340Z [CURL DBG] < Content-Type: application/xml
2022-11-15T01:37:56.340Z [CURL DBG] < Server: xxxx
2022-11-15T01:37:56.341Z [CURL DBG] < Access-Control-Expose-Headers: Etag
2022-11-15T01:37:56.341Z [CURL DBG] < Access-Control-Allow-Origin: *
2022-11-15T01:37:56.341Z [CURL DBG] < Date: Tue, 15 Nov 2022 01:37:56 GMT
2022-11-15T01:37:56.341Z [CURL DBG] < Connection: close
2022-11-15T01:37:56.341Z [CURL DBG] < Content-Length: 341
2022-11-15T01:37:56.342Z [CURL DBG] <
2022-11-15T01:37:56.342Z [CURL DBG] * Closing connection 0
```

**Comment by ggtakec** [comment]
@huntersman Thanks for your log.
I noticed from your log that the following path in the log is strange.
```
PUT /demo// HTTP/1.1
```
This was a potential bug in s3fs and had been fixed by #2057.
(I think this bug affects this PR.)
#2057 had been merged and this PR also rebased the merged code.

Are you specifying `<bucket name>:/demo//` when starting s3fs?
I haven't been able to get this same log output otherwise yet.
And I haven't been able to reproduce the `path(/) is not parent directory.` error message that you first pointed out.
However, this fix may have fixed it.

If possible, could you try again with the corrected code in this PR?

**Comment by huntersman** [comment]
Thank you for your code. I try it, but it doesn't work. Maybe it's because I use self-maintained object storage, not Amazon S3.

**Comment by ggtakec** [comment]
@huntersman 
OK, it looks like correct access.
The bug before  fixing of #2057 and the code in this PR may cause problems with the objects in your S3 bucket/folder, so make sure the object `/demo//` is not created please confirm.
If it exists, try to remove it from the UI, CLI tools, etc.
Thanks in advance for your help.

**Comment by ggtakec** [comment]
@gaul I will merge this PR.
This feature works only when the `update_parent_dir_stat` option is given, so it does not affect users (existing) who do not specify the option.
Please let me know if you have any problems.

**Pull request merged**
