### PR TITLE
Add curl handler pool to reuse connections

### PR DESCRIPTION
**Pull request by rockuw**
Currently s3fs creates a new tcp connection for each request to s3. Together with the fact that curl(or HTTP) defaults to use 'Connection:keep-alive', the client may ends with lots of 'TIME_WAIT' connections:

```
ubuntu@ip-172-31-29-108:~/s3fs-fuse$ for i in $(seq 100); do ls /tmp/s3fs > /dev/null; done
ubuntu@ip-172-31-29-108:~/s3fs-fuse$ sudo ss -tan | grep TIME | wc -l
101
```

This patches enables reusing curl handlers and thus utilizes HTTP keep-alive, which has the effects:

1. boost performance
2. largely reduce TIME_WAIT connections

### CODE REVIEW

**Comment by RobbKistler** [comment]
Does AWS S3 actually respect keep-alive? I thought it didn't.  Other S3 providers might.

**Comment by rockuw** [comment]
@RobbKistler Why shouldn't it? Since s3 provides RESTful API, which implies HTTP, which implies 'Connection' header.

**Comment by rockuw** [comment]
@RobbKistler And the 101 connections of 'TIME_WAIT' is an indication that s3 respects 'keep-alive' and **does not close the connection** after the HTTP request. The client then closes it and enters 'TIME_WAIT'. (Only the part who initiates FIN enters this state).

**Comment by RobbKistler** [comment]
@rockuw I was recalling information in this thread:

https://forums.aws.amazon.com/thread.jspa?threadID=12062

But the thread is very old and probably outdated.

**Comment by rockuw** [comment]
@RobbKistler As  John Cormie(from S3) says:

> This should be fixed now. Sorry about the inconvenience.

**Comment by rockuw** [comment]
@ggtakec

**Comment by ggtakec** [comment]
@rockuw @RobbKistler 
If s3fs can use the KeepAlive, I think it will give a good performance and reduce the resources.
Thus I'm going to merge this PR, and to test it.
If you found bugs about KeepAlive, please post issue.

**Pull request merged**
