### PR TITLE
Explicitly `grep` for `ps` args

### PR DESCRIPTION
**Pull request by gaul**

### CODE REVIEW

**Comment by gaul** [comment]
Older shellcheck appear to have a false positive for this idiom.

**Review by ggtakec — COMMENTED** [review]
Thank you, this `-o args` option is useful.
By the way, since the current command outputs multiple lines, how about adding `--no-headers` as well?

**Comment by gaul** [comment]
> By the way, since the current command outputs multiple lines, how about adding `--no-headers` as well?

Done.  Not sure if macOS supports this but I abstracted it to a function.

**Review by ggtakec — APPROVED** [review]
Thank s for updating.

`--no-headers` option seems that it is not supported by macos.
It looks like I'll be using PIPE instead and extracting with something like `| tail -n +2`.
But I will modify that this will be inspected and changed when the macos will be supported.

**Pull request merged**
