### PR TITLE
Add install instructions for Arch Linux

### PR DESCRIPTION
**Pull request by migueldvb**
### Details

Add install instructions for Arch Linux

### CODE REVIEW

**Comment by gaul** [comment]
Thank you for your contribution @migueldvb!

**Comment by juliogonzalez** [comment]
Should we maybe add installation from source at https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes ?

It's useful if a user needs to test something from master, a branch, etc.

**Comment by gaul** [comment]
Does https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#from-github-repository cover this?  If not let's continue discussing doc improvements in a separate issue.  At least we can remove distributions that are end of life like Ubuntu 10.04 - 12.04.

**Comment by juliogonzalez** [comment]
@gaul I was talking about https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#notes-for-specific-operating-systems, as it's only there were the packages that are required to build and run are listed.

In fact https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#general-instructions should be probably part of https://github.com/s3fs-fuse/s3fs-fuse/blob/master/COMPILATION.md

**Comment by gaul** [comment]
@juliogonzalez Ah I understand, it would be nice to have Arch compilation instructions as well.  Agreed that this makes more sense as part of COMPILATION.md.  I also made some edits to remove the stale Ubuntu 10.04 and 12.04 instructions although we should also refresh 14.04 to 16.04 given that the former is EOL.

**Pull request merged**
