### PR TITLE
Configure Travis with Ubuntu Xenial

### PR DESCRIPTION
**Pull request by gaul**
Trusty end of life was April 2019.

### CODE REVIEW

**Comment by gaul** [comment]
@ggtakec This has an interesting failure in `test_multipart_mix`.  Maybe an existing issue?

**Comment by gaul** [comment]
This is a spurious failure caused by gaul/s3proxy#303.  I restarted the build.

**Comment by gaul** [comment]
Huh, it seems like the newer Linux distribution triggers this S3Proxy race reliably.  Let's wait until the next S3Proxy release.

**Comment by ggtakec** [comment]
understood. Wait for s3proxy.

**Pull request closed without merging**
