### PR TITLE
Add Travis configuration

### PR DESCRIPTION
**Pull request by andrewgaul**

### CODE REVIEW

**Comment by andrewgaul** [comment]
@ggtakec Could you merge this commit and add s3fs-fuse to https://travis-ci.org/repositories?  Although Travis cannot run the integration tests due to travis-ci/travis-ci#1100, it does run the handful of unit tests.

**Comment by ggtakec** [comment]
@andrewgaul I added s3fs-fuse to travis-ci
I set only "Build only if .travis.yml is present" option in setting, so if you need to set another options, please let me know.
Thanks a lot.

**Comment by andrewgaul** [comment]
@ggtakec I don't see any build results for #147 at https://travis-ci.org/s3fs-fuse/s3fs-fuse.  This should not need any additional options; https://travis-ci.org/andrewgaul/s3fs-fuse worked in my testing.

**Comment by andrewgaul** [comment]
It looks like pull requests are disabled:

https://travis-ci.org/s3fs-fuse/s3fs-fuse/requests

**Comment by ggtakec** [comment]
@andrewgaul I checked "Build pushes" and "Build pull requests" attributes.

**Comment by andrewgaul** [comment]
Excellent I now see the PR builder: https://github.com/s3fs-fuse/s3fs-fuse/pull/147

**Pull request merged**
