### PR TITLE
Improved fdcache_page performance

### PR DESCRIPTION
**Pull request by ggtakec**
### Relevant Issue (if applicable)
#2019 #2027

### Details
The following issues were reported.
- High CPU load when running s3fs (#2027)
- Extremely poor performance in `fio` test with multi number of job (#2019)

Both of these seem to be caused by the processing by the `page list` of `fdcache` operation in the `PageList` class.
There was a problem with `page list` compress and data extraction logic, resulting in poor performance.

Below are the values when measured with `gprof`:
```
 %   cumulative   self              self     total
time   seconds   seconds    calls  us/call  us/call  name
71.51      1.33     1.33    49576    26.83    26.83  raw_compress_fdpage_list(std::__cxx11::list<fdpage, std::allocator<fdpage> > const&, bool, bool, bool, bool) [clone .constprop.56]
13.44      1.58     0.25    12672    19.73    19.73  PageList::BytesModified() const
10.22      1.77     0.19    13184    14.41    14.41  PageList::GetTotalUnloadedPageSize(long, long, long) const
 3.76      1.84     0.07    49567     1.41    28.24  PageList::Compress()
 0.54      1.85     0.01    24964     0.40    28.22  PageList::SetPageLoadedStatus(long, long, PageList::page_status, bool)
...
...
```

Reviewed related functions including `raw_compress_fdpage_list` in problem.(Reduced useless copies, etc.)
I have confirmed that this fix does not cause a high load on the CPU.

### CODE REVIEW

**Comment by bhuvanp1305** [comment]
@ggtakec @gaul any timeline for the merge of this PR?

**Comment by ggtakec** [comment]
@bhuvanp1305 Sorry to keep you waiting, please wait a little longer.
Is it possible for you to try this code?

**Comment by SanjeetKr7** [comment]
@ggtakec 
Yes we tried this code and installed all the required dependencies in our container.
```dependencies = automake gcc-c++ make git tar libcurl-devel libxml2-devel openssl-devel mailcap fuse```

but It is not able to mount the file from s3 bucket and we are getting this error
```
sftp_user2@sftp-server-84c69445fd-p87lr tmp]$ cat tmp__home_sftp_user2_nedata_perfs.log
2022-09-08T05:37:16.750Z [INF] curl.cpp:InitMimeType(428): Loaded mime information from /etc/mime.types
2022-09-08T05:37:16.754Z [INF] s3fs.cpp:s3fs_init(3502): init v1.91(commit:1946ac4) with OpenSSL
2022-09-08T05:37:38.357Z [ERR] s3fs_xml.cpp:get_base_exp(113): marker_xp->nodesetval is empty.
2022-09-08T05:42:31.517Z [ERR] s3fs_xml.cpp:get_base_exp(113): marker_xp->nodesetval is empty.```

**Comment by ggtakec** [comment]
@SanjeetKr7 
I think this error in `get_base_exp` has nothing to do with the modified code in this PR.
The part fixed in this PR is related to the local cache of files (objects).
I think the `get_base_exp` error is related to `listbucket`, so is it occurring even if the PR code is not adapted?
(If so, I'm sure it's something else.)

**Comment by SanjeetKr7** [comment]
> @SanjeetKr7 I think this error in `get_base_exp` has nothing to do with the modified code in this PR. The part fixed in this PR is related to the local cache of files (objects). I think the `get_base_exp` error is related to `listbucket`, so is it occurring even if the PR code is not adapted? (If so, I'm sure it's something else.)

It was not occurring before the PR code adopted

**Comment by SanjeetKr7** [comment]
@ggtakec @gaul 
We were not facing any type of file mounting issue(get_base_exp error) with `v1.89` and `v1.91` of s3fs-fuse. This issue only appears after taking the source of this PR
``` 
Able to mount the files
	ocp lab + alpine image Dockerfile + s3fs v1.89  => successful
	ocp lab + alpine image Dockerfile + s3fs v1.91  => successful
Not able to mount the files
	ocp lab + alpine image Dockerfile + s3fs master => failing
patch is on top of master
        ocp lab + alpine image Dockerfile + s3fs master + patch => failing
```
Due to this issue, we deviated from our original issue which is CPU high usage. Please help us to resolve this issue so that we can focus on our main concern of CPU high usage.

**Comment by ggtakec** [comment]
@SanjeetKr7 
I think your error has a different cause than the fix code in this PR.
Probably, the current master code (changed from v1.91) seems to be the cause.

Is it possible to check a little more detailed log by adding `dbglevel=dbg` and `curldbg` options?
I have created a separate issue(#2036), so please let me know the detailed results there.

**Pull request merged**
