### PR TITLE
Simplify installation for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by gaul**
Also reorganize installation vs. compilation.

### CODE REVIEW

**Comment by orozery** [comment]
@gaul this won't install the latest s3fs version, right?

**Comment by gaul** [comment]
Newer versions of Ubuntu track the later s3fs versions, with 18.04 packaging 1.82 but 16.04 packaging 1.79:

https://packages.ubuntu.com/bionic/s3fs
https://packages.ubuntu.com/xenial/utils/s3fs

Homebrew packages the latest 1.83:

https://formulae.brew.sh/formula/s3fs

I would like to recommend that users install the distro packages which will provide a better experience for non-developers.  However we should continue to provide the compilation instructions for all users if they have a particular bug.  This gets a bit dicey when we know about a data loss bug but I believe we fixed most of those before 1.79.

**Comment by orozery** [comment]
There are bug fixes and many performance improvements (certainly when comparing 1.79 to 1.83 or the master branch).
We can include instructions on installing from a package, but we should add a disclosure (I think we should recommend installing from source as you get the latest version).

**Comment by gaul** [comment]
Software is never finished and a given distribution ships lots of software that does not have the most recent version number.  I do not see anything unique about s3fs that would cause us to recommend that everyone compiles from source.  However, for data loss bugs we may want to notify LTS releases like Ubuntu 18.04.

**Comment by orozery** [comment]
@gaul and can't we update the ubuntu package to a newer s3fs version? (like `pip install <python_package>` always gets you the latest version)

**Comment by ggtakec** [comment]
@gaul @orozery We will update the README from time to time if there are additional notes, so I will merge this PR.
I hope I can do something like LTS releases ...

**Comment by gaul** [comment]
@orozery C++ package managers never took off in the Linux world the way `pip` did for Python and other non-compiled languages, likely because the problem is more difficult.

**Comment by spolischook** [comment]
This is no longer true. Installation from apt is not working on Ubuntu 16.04.
How ever compiled version works very well

**Comment by gaul** [comment]
@spolischook Could you share the output of the failed apt-get install?

**Comment by spolischook** [comment]
Sorry, I have got another issue with dots in backet name - https://github.com/s3fs-fuse/s3fs-fuse/issues/284
Now it works.
And, yea, there was no error code, command finish with success, however it's all about https://github.com/s3fs-fuse/s3fs-fuse/issues/284

**Pull request merged**
