### PR TITLE
added fuse package for mounting via /etc/fstab, fixes #417

### LINKED ISSUE #417: mounting via /etc/fstab
Debian 8.3 x 64

Basic mounting via /etc/fstab results in the following error message `sudo mount -a`.  Any ideas on how to debug this further?

```
mount: wrong fs type, bad option, bad superblock on s3fs#s3fs-test.domain.com,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

Mounting via command line works

```
sudo s3fs s3fs-test.domain.com /mnt/s3fs-test -o allow_other -o passwd_file=/etc/passwd-s3fs -d -d -f -o f2 -o curldbg
```

_Note: s3fs is doing it's job trying to figure out the endpoint/region, bucket is on us-west-1_

Translating this to /etc/fstab as follows

```
...
s3fs#s3fs-test.domain.com	/mnt/s3fs-test	fuse	_netdev,allow_other	,dbglevel=dbg 0	0
...
```

Doing a `sudo tail -f /var/log/messages` and `sudo tail -f /var/log/syslod` does not show any error messages.  

* It almost seems like `sudo mount -a` cannot find `s3fs`?
* Tried `sudo apt-get install nfs-common` and `sudo apt-get install cifs-utils` with no luck
* How does the /etc/fstab find the `/etc/passwd-s3fs`, do you have to specify that in the options?

### PR DESCRIPTION
**Pull request by dsulli99**
added fuse package for mounting via /etc/fstab, fixes #417

### CODE REVIEW

**Comment by andrewgaul** [comment]
Please reorder this alphabetically.

**Comment by dsulli99** [comment]
Done.  Let me know if you want me to rebase/squash into a single commit.

**Comment by andrewgaul** [comment]
Please squash these commits.

**Comment by dsulli99** [comment]
Done.

**Comment by ggtakec** [comment]
@dsulli99 Thanks for your help.

**Pull request merged**
