### PR TITLE
Fix double-iteration in curl_slist_remove

### PR DESCRIPTION
**Pull request by gaul**
Also backfill tests.  Fixes #1948.

### CODE REVIEW

**Comment by gaul** [comment]
@nkkashyap can you test this against IBM to see if it resolves your symptoms?

@ggtakec I think this is a simpler approach that includes more test coverage.

**Review by ggtakec — APPROVED** [review]

**Comment by ggtakec** [comment]
@gaul Thank you for the test code. (I forgot test_curl_util.cpp)
I don't think there is any problem with this test.
Also, this PR is simpler than the fix for #1950, so once it's merged, #1950 will close.

**Review by nkkashyap — APPROVED** [review]
PR looks good

**Comment by ggtakec** [comment]
@nkkashyap Thanks for your help.

**Pull request merged**
